apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: DS_PROMETHEUS
    url: http://prometheus:9090/prometheus
    isDefault: true
    jsonData:
      timeInterval: 2s
    editable: true
